namespace Brauser.Common.Import;

/// <summary>
///     Json export of a recipe from the german site <see cref="https://www.maischemalzundmehr.de/" />
/// </summary>
/// <param name="Name"></param>
/// <param name="Datum"></param>
/// <param name="Sorte"></param>
/// <param name="Ausschlagswuerze"></param>
/// <param name="Sudhausausbeute"></param>
/// <param name="Stammwuerze"></param>
/// <param name="Bittere"></param>
/// <param name="Farbe"></param>
/// <param name="Alkohol"></param>
/// <param name="Kurzbeschreibung"></param>
/// <param name="Infusion_Hauptguss"></param>
/// <param name="Malz1"></param>
/// <param name="Malz1_Menge"></param>
/// <param name="Malz1_Einheit"></param>
/// <param name="Malz2"></param>
/// <param name="Malz2_Menge"></param>
/// <param name="Malz2_Einheit"></param>
/// <param name="Malz3"></param>
/// <param name="Malz3_Menge"></param>
/// <param name="Malz3_Einheit"></param>
/// <param name="Maischform"></param>
/// <param name="Infusion_Einmaischtemperatur"></param>
/// <param name="Infusion_Rasttemperatur1"></param>
/// <param name="Infusion_Rastzeit1"></param>
/// <param name="Infusion_Rasttemperatur2"></param>
/// <param name="Infusion_Rastzeit2"></param>
/// <param name="Infusion_Rasttemperatur3"></param>
/// <param name="Infusion_Rastzeit3"></param>
/// <param name="Abmaischtemperatur"></param>
/// <param name="Nachguss"></param>
/// <param name="Kochzeit_Wuerze"></param>
/// <param name="Hopfen_VWH_1_Sorte"></param>
/// <param name="Hopfen_VWH_1_Menge"></param>
/// <param name="Hopfen_VWH_1_alpha"></param>
/// <param name="Hopfen_1_Sorte"></param>
/// <param name="Hopfen_1_Menge"></param>
/// <param name="Hopfen_1_alpha"></param>
/// <param name="Hopfen_1_Kochzeit"></param>
/// <param name="Hopfen_2_Sorte"></param>
/// <param name="Hopfen_2_Menge"></param>
/// <param name="Hopfen_2_alpha"></param>
/// <param name="Hopfen_2_Kochzeit"></param>
/// <param name="Hefe"></param>
/// <param name="Gaertemperatur"></param>
/// <param name="Endvergaerungsgrad"></param>
/// <param name="Karbonisierung"></param>
/// <param name="Anmerkung_Autor"></param>
public record MaischeMalzUndMehrRecipe(
    string Name,
    string Datum,
    string? Sorte = null,
    int? Ausschlagswuerze = null,
    int? Sudhausausbeute = null,
    int? Stammwuerze = null,
    int? Bittere = null,
    string? Farbe = null,
    double? Alkohol = null, // Check if double is correct
    string? Kurzbeschreibung = null,
    int? Infusion_Hauptguss = null,
    string? Malz1 = null,
    double? Malz1_Menge = null,
    string? Malz1_Einheit = null,
    string? Malz2 = null,
    double? Malz2_Menge = null,
    string? Malz2_Einheit = null,
    string? Malz3 = null,
    double? Malz3_Menge = null,
    string? Malz3_Einheit = null,
    string? Maischform = null,
    double? Infusion_Einmaischtemperatur = null,
    string? Infusion_Rasttemperatur1 = null,
    string? Infusion_Rastzeit1 = null,
    string? Infusion_Rasttemperatur2 = null,
    string? Infusion_Rastzeit2 = null,
    string? Infusion_Rasttemperatur3 = null,
    string? Infusion_Rastzeit3 = null,
    string? Abmaischtemperatur = null,
    int? Nachguss = null,
    string? Kochzeit_Wuerze = null,
    string? Hopfen_VWH_1_Sorte = null,
    int? Hopfen_VWH_1_Menge = null,
    int? Hopfen_VWH_1_alpha = null,
    string? Hopfen_1_Sorte = null,
    int? Hopfen_1_Menge = null,
    int? Hopfen_1_alpha = null,
    string? Hopfen_1_Kochzeit = null,
    string? Hopfen_2_Sorte = null,
    int? Hopfen_2_Menge = null,
    int? Hopfen_2_alpha = null,
    string? Hopfen_2_Kochzeit = null,
    string? Hefe = null,
    string? Gaertemperatur = null,
    string? Endvergaerungsgrad = null,
    string? Karbonisierung = null,
    string? Anmerkung_Autor = null
);