//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brauser.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Brauser {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Brauser() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Brauser.Common.Resources.Brauser", typeof(Brauser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BatchSize {
            get {
                return ResourceManager.GetString("BatchSize", resourceCulture);
            }
        }
        
        internal static string BrewhouseYield {
            get {
                return ResourceManager.GetString("BrewhouseYield", resourceCulture);
            }
        }
        
        internal static string OriginalGravity {
            get {
                return ResourceManager.GetString("OriginalGravity", resourceCulture);
            }
        }
        
        internal static string Bitterness {
            get {
                return ResourceManager.GetString("Bitterness", resourceCulture);
            }
        }
        
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        internal static string Alcohol {
            get {
                return ResourceManager.GetString("Alcohol", resourceCulture);
            }
        }
        
        internal static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        internal static string MashWater {
            get {
                return ResourceManager.GetString("MashWater", resourceCulture);
            }
        }
        
        internal static string Malt {
            get {
                return ResourceManager.GetString("Malt", resourceCulture);
            }
        }
        
        internal static string MashingTemperature {
            get {
                return ResourceManager.GetString("MashingTemperature", resourceCulture);
            }
        }
        
        internal static string Infusion {
            get {
                return ResourceManager.GetString("Infusion", resourceCulture);
            }
        }
        
        internal static string MashoutTemperature {
            get {
                return ResourceManager.GetString("MashoutTemperature", resourceCulture);
            }
        }
        
        internal static string SpargeWater {
            get {
                return ResourceManager.GetString("SpargeWater", resourceCulture);
            }
        }
        
        internal static string WortBoilingTime {
            get {
                return ResourceManager.GetString("WortBoilingTime", resourceCulture);
            }
        }
        
        internal static string Hop {
            get {
                return ResourceManager.GetString("Hop", resourceCulture);
            }
        }
        
        internal static string DryHop {
            get {
                return ResourceManager.GetString("DryHop", resourceCulture);
            }
        }
        
        internal static string Yeast {
            get {
                return ResourceManager.GetString("Yeast", resourceCulture);
            }
        }
        
        internal static string FermentationTemperature {
            get {
                return ResourceManager.GetString("FermentationTemperature", resourceCulture);
            }
        }
        
        internal static string Carbonation {
            get {
                return ResourceManager.GetString("Carbonation", resourceCulture);
            }
        }
        
        internal static string Variety {
            get {
                return ResourceManager.GetString("Variety", resourceCulture);
            }
        }
        
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        internal static string CookingTime {
            get {
                return ResourceManager.GetString("CookingTime", resourceCulture);
            }
        }
        
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        internal static string RestTemperature {
            get {
                return ResourceManager.GetString("RestTemperature", resourceCulture);
            }
        }
        
        internal static string RestTime {
            get {
                return ResourceManager.GetString("RestTime", resourceCulture);
            }
        }
        
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
    }
}
