name: Publish nuget package
on:
  push:
    branches: [ "main" ]
env:
  DOTNET_VERSION: '7.0.x'
jobs:
  push:
    name: Publish NuGet Package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: pack nuget
      run: dotnet pack --configuration Release --version-suffix "preview${{ github.run_id }}"
      
    - name: Publish nuget
      run: dotnet nuget push Brauser.Common/bin/Release/Brauser.Common.1.0.0-preview${{ github.run_id }} --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"


