name: Publish nuget package

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Solution_Name: Brauser.Common.sln  

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore solution
      run: dotnet restore

    # Execute all unit tests in the solution
    - name: pack nuget
      run: dotnet pack --configuration Release --version-suffix "preview${{ github.run_id }}"
      
    - name: Publish nuget
      run: dotnet nuget push Brauser.Common/bin/Release/Brauser.Common.1.0.0-prefiew${{ github.run_id }} --api-key ${{ secrets.GITHUB_TOKEN }}


